source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/masterprash2/ios-segment-spec.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PowerAdaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PowerAdaper
  
   pod 'PowerAdapter', '0.2.8'
  

  target 'PowerAdaperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
